language: ruby
services:
  - postgresql
before_script:
  - sudo -u postgres psql -c "CREATE USER askthem SUPERUSER;"
  - bin/rails db:create RAILS_ENV=test
  - bin/rails db:migrate RAILS_ENV=test
addons:
  postgresql: "9.6"

